### ISSUE TITLE
Add missing babeljs

### ISSUE THREAD

**Issue by jschlyter** [Lundix-IT/spcbridge-card#2]
Something is missing for the build CI to succeed, see https://github.com/Lundix-IT/spcbridge-card/actions/runs/12211319115/job/34068443814

**Comment by Goran58** [comment]
Actually, I’m not sure if it’s entirely necessary to use babeljs. So for now, I think we should remove that step. Please update the `package.json` file to:
`...
"scripts": {
    "build": "npm run lint && npm run rollup",
    "rollup": "rollup -c",
    "lint": "eslint --fix src/*.ts",
    "start": "rollup -c --watch"
  },
  ....
`
Regarding the warning, I also get it in my own build environment. I haven’t been able to determine what’s causing it, but I haven’t noticed any negative impact, so I’ve left it as is.
